services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db # Example, replace with actual DB connection string or secrets
    depends_on:
      - frontend # Ensure frontend is up before backend for Nginx proxying if needed, though usually backend doesn't depend on frontend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html # Mount frontend files for live changes during development
